apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kristianteppan
helmCharts:
  - name: podtato-head
    repo: https://charts.portefaix.xyz/
    version: 0.3.0
    releaseName: podtato-head
    namespace: kristianteppan
    valuesFile: values.yaml
    additionalValuesFiles:
      - ./wood-legs-crab/values.yaml

resources:
  - http-route.yaml
